import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/About.module.css'
import Header from "../components/assets/header/Header"
import Footer from "../components/assets/footer/Footer"
import {motion} from 'framer-motion'


export default function Home() {
  return (

    <div className={styles.container}>
      <Header/>
      <Head>
        <title>Tragdie Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main class="home">
        <div class="home-banner">
        <Image src ={`/../public/banners/imagem/Banner-1536x864.png`}
          width={1536}
          height={864}>
        </Image>
        </div>
        <div class="services-menu">

        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          class="call-to-services">
          <div class="about-tag">
            <h3>Branding </h3>
            <div class="standard-btn">
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          class="call-to-services">
          <div class="about-tag">
            <h3>Branding </h3>
            <div class="standard-btn">
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          class="call-to-services">
          <div class="services-tag">
            <h3>Branding </h3>
            <div class="standard-btn">
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          class="call-to-services">
          <div class="services-tag">
            <h3>Branding </h3>
            <div class="standard-btn">
            Clique aqui
            </div>
            </div>
          </motion.div>
        <motion.div
          animate={{scale:1}}
        whileHover={{scale:1.3}}
          class="call-to-services">
          <div class="services-tag">
            <h3>Branding </h3>
            <div class="standard-btn">
            Clique aqui
            </div>
            </div>
          </motion.div>
        </div>

        <div class="call-to-about">
        <h3> DESIGN PARA
ATINGIR NOVOS PATAMARES</h3>
          <p>Peças de design criadas com compromisso, seriedade e respeitando a sua identidade visual, pois a linguagem do seu negócio é muito importante, e o design atrativo devem andar lado a lado com a sua marca.
          </p>
      <motion.div
        animate={{scale:1}}
        whileHover={{scale:1.3}} class="standard-btn">
        Conheça
      </motion.div>


        </div>


  </main>
    <Footer/>


    </div>
  )
}
